import torch

# LEARNING PARAMETERS
GAMMA = 0.99
BATCH_SIZE = 64
BUFFER_SIZE = int(1e6)
TAU = 1e-1
LR_ACTOR = 5e-3
LR_CRITIC = 5e-3
WEIGHT_DECAY = 0.0001
UPDATE_EVERY = 5

# NOISE PARAMETERS
INITIAL_NOISE_WEIGHT = 0.3
NOISE_REDUCTION_FACTOR = 0.99999
THETA = 0.15
MU = 0
SIGMA = 0.2

# DEVICE PARAMETERS
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
