import torch

# LEARNING PARAMETERS
GAMMA = 0.99
BATCH_SIZE = 128
BUFFER_SIZE = int(1e5)
TAU = 1e-2
LR_ACTOR = 5e-3
LR_CRITIC = 5e-4
WEIGHT_DECAY = 0.0001
UPDATE_EVERY = 20

# NOISE PARAMETERS
NOISE_INITIAL_WEIGHT = 0.8
NOISE_REDUCTION_FACTOR = 0.999999
NOISE_THETA = 0.15
NOISE_MU = 0
NOISE_SIGMA = 0.5

# DEVICE PARAMETERS
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
